using System.Globalization;
using System.Text;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;

namespace FractalBlazor.Components.Tools
{
    internal static class ImageToColorArray
    {
        private static readonly HashSet<string> ReservedKeywords = new(StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class",
            "const", "continue", "decimal", "default", "delegate", "do", "double", "else", "enum", "event",
            "explicit", "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto", "if",
            "implicit", "in", "int", "interface", "internal", "is", "lock", "long", "namespace", "new", "null",
            "object", "operator", "out", "override", "params", "private", "protected", "public", "readonly", "ref",
            "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string", "struct", "switch",
            "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using",
            "virtual", "void", "volatile", "while"
        };

        public static void ImportStandard()
            => GenerateColorPaletteArray("tw-color-palette.png", 8, 8, "FbBaseColors", "FbBaseColors.cs");

        /// <summary>
        /// Open the png file and generate a color palette cs file as a two-dimensional C# array of web color strings (like "#458735").
        /// It takes the center pixel of each square. Array size is the result of the image size.
        /// </summary>
        /// <param name="filePath">A png file path.</param>
        /// <param name="searchLimit">If the file is not found, search for it in parent directories up to this number of levels.</param>
        /// <param name="squareSize">The size of each color square in the image.</param>
        /// <param name="arrayName">The name of the generated array.</param>
        /// <param name="outputFilePath">The path of the generated C# file.</param>
        public static void GenerateColorPaletteArray(string filePath, int searchLimit, int squareSize, string arrayName, string outputFilePath)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(filePath);
            ArgumentOutOfRangeException.ThrowIfNegative(searchLimit);
            ArgumentOutOfRangeException.ThrowIfNegativeOrZero(squareSize);
            ArgumentException.ThrowIfNullOrWhiteSpace(arrayName);
            ArgumentException.ThrowIfNullOrWhiteSpace(outputFilePath);

            if (!IsValidIdentifier(arrayName))
            {
                throw new ArgumentException($"'{arrayName}' is not a valid C# identifier.", nameof(arrayName));
            }

            string resolvedFilePath = FindFile(filePath, searchLimit);

            using Image<Rgba32> image = Image.Load<Rgba32>(resolvedFilePath);

            if (image.Width % squareSize != 0 || image.Height % squareSize != 0)
            {
                throw new InvalidDataException(
                    $"Image dimensions ({image.Width}x{image.Height}) must be divisible by the square size ({squareSize}).");
            }

            int columnCount = image.Width / squareSize;
            int rowCount = image.Height / squareSize;
            int centerOffset = squareSize / 2;
            var result = new StringBuilder();

            result.AppendLine("// <auto-generated />");
            result.Append("public static readonly string[,] ")
                .Append(arrayName)
                .AppendLine(" = new string[,]")
                .AppendLine("{");

            for (int row = 0; row < rowCount; row++)
            {
                result.Append("    { ");

                for (int column = 0; column < columnCount; column++)
                {
                    Rgba32 color = image[column * squareSize + centerOffset, row * squareSize + centerOffset];

                    if (column > 0)
                    {
                        result.Append(", ");
                    }

                    result.Append('"')
                        .Append('#')
                        .Append(color.R.ToString("X2", CultureInfo.InvariantCulture))
                        .Append(color.G.ToString("X2", CultureInfo.InvariantCulture))
                        .Append(color.B.ToString("X2", CultureInfo.InvariantCulture))
                        .Append('"');
                }

                result.AppendLine(row < rowCount - 1 ? " }," : " }");
            }

            result.AppendLine("};");

            string resolvedOutputPath = Path.GetFullPath(outputFilePath);
            StringComparison pathComparison = OperatingSystem.IsWindows()
                ? StringComparison.OrdinalIgnoreCase
                : StringComparison.Ordinal;
            if (string.Equals(resolvedFilePath, resolvedOutputPath, pathComparison))
            {
                throw new IOException("The output file cannot overwrite the source image.");
            }

            string? outputDirectory = Path.GetDirectoryName(resolvedOutputPath);
            if (outputDirectory is not null)
            {
                Directory.CreateDirectory(outputDirectory);
            }

            File.WriteAllText(resolvedOutputPath, result.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        }

        private static string FindFile(string filePath, int searchLimit)
        {
            if (Path.IsPathFullyQualified(filePath))
            {
                if (File.Exists(filePath))
                {
                    return Path.GetFullPath(filePath);
                }

                throw new FileNotFoundException("The palette image could not be found.", filePath);
            }

            DirectoryInfo? directory = new(Directory.GetCurrentDirectory());

            for (int level = 0; level <= searchLimit && directory is not null; level++, directory = directory.Parent)
            {
                string candidate = Path.GetFullPath(Path.Combine(directory.FullName, filePath));
                if (File.Exists(candidate))
                {
                    return candidate;
                }
            }

            throw new FileNotFoundException(
                $"The palette image '{filePath}' could not be found in the current directory or within {searchLimit} parent director{(searchLimit == 1 ? "y" : "ies")}.",
                filePath);
        }

        private static bool IsValidIdentifier(string value)
        {
            int start = value[0] == '@' ? 1 : 0;
            if (start == value.Length
                || !IsIdentifierStart(value[start])
                || (start == 0 && ReservedKeywords.Contains(value)))
            {
                return false;
            }

            for (int index = start + 1; index < value.Length; index++)
            {
                if (!IsIdentifierPart(value[index]))
                {
                    return false;
                }
            }

            return true;
        }

        private static bool IsIdentifierStart(char value)
        {
            UnicodeCategory category = char.GetUnicodeCategory(value);
            return value == '_'
                || category == UnicodeCategory.UppercaseLetter
                || category == UnicodeCategory.LowercaseLetter
                || category == UnicodeCategory.TitlecaseLetter
                || category == UnicodeCategory.ModifierLetter
                || category == UnicodeCategory.OtherLetter
                || category == UnicodeCategory.LetterNumber;
        }

        private static bool IsIdentifierPart(char value)
        {
            UnicodeCategory category = char.GetUnicodeCategory(value);
            return IsIdentifierStart(value)
                || category == UnicodeCategory.DecimalDigitNumber
                || category == UnicodeCategory.ConnectorPunctuation
                || category == UnicodeCategory.NonSpacingMark
                || category == UnicodeCategory.SpacingCombiningMark
                || category == UnicodeCategory.Format;
        }
    }
}
